image: python:3.11

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - pip install -r requirements.txt
    - pip install flake8
    - flake8 --max-line-length=120 --ignore=F401,F403 src
  only:
    - merge_requests

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/diplomka_backend && git pull $REPO && docker compose up -d --build app && docker system prune -af"
  environment:
    name: production
    url: http://$SERVER_IP
  only:
    - main
