image: node:latest

stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment_front
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/vkr_front && git pull $REPO && npm install && npm run build"
  environment:
    name: production
    url: http://$SERVER_IP
  only:
    - main
