"""Init database

Revision ID: 8b171dbe6695
Revises: 
Create Date: 2023-02-25 14:46:15.403055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b171dbe6695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_have_signature', sa.Boolean(), nullable=True),
    sa.Column('inn', sa.String(length=14), nullable=True),
    sa.Column('type', sa.Enum('admin', 'client', 'meauser', 'designer', 'manager', 'builder', name='type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('meauser_id', sa.Integer(), nullable=True),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('builder_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('series', sa.Enum('S1', 'S2', 'S3', 'S4', 'S5', 'S6', name='series'), nullable=True),
    sa.Column('room_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', name='status'), nullable=True),
    sa.Column('is_contract_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_text', sa.String(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['builder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['meauser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_date', sa.DateTime(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_id'), 'design', ['id'], unique=False)
    op.create_table('finish_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finish_doc_id'), 'finish_doc', ['id'], unique=False)
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('come_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_id'), 'measurement', ['id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_table('order_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_check_id'), 'order_check', ['id'], unique=False)
    op.create_table('order_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_room_id'), 'order_room', ['id'], unique=False)
    op.create_table('order_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_signature_id'), 'order_signature', ['id'], unique=False)
    op.create_table('pre_work_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_file', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_work_doc_id'), 'pre_work_doc', ['id'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_id'), 'stage', ['id'], unique=False)
    op.create_table('comment_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_design_id'), 'comment_design', ['id'], unique=False)
    op.create_table('finish_doc_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('finish_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finish_doc_id'], ['finish_doc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finish_doc_signature_id'), 'finish_doc_signature', ['id'], unique=False)
    op.create_table('order_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_room_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_room_id'], ['order_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_image_id'), 'order_image', ['id'], unique=False)
    op.create_table('pre_work_doc_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pre_work_doc_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pre_work_doc_id'], ['pre_work_doc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_work_doc_comment_id'), 'pre_work_doc_comment', ['id'], unique=False)
    op.create_table('sample_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_image_id'), 'sample_image', ['id'], unique=False)
    op.create_table('stage_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_image_id'), 'stage_image', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_image_id'), table_name='stage_image')
    op.drop_table('stage_image')
    op.drop_index(op.f('ix_sample_image_id'), table_name='sample_image')
    op.drop_table('sample_image')
    op.drop_index(op.f('ix_pre_work_doc_comment_id'), table_name='pre_work_doc_comment')
    op.drop_table('pre_work_doc_comment')
    op.drop_index(op.f('ix_order_image_id'), table_name='order_image')
    op.drop_table('order_image')
    op.drop_index(op.f('ix_finish_doc_signature_id'), table_name='finish_doc_signature')
    op.drop_table('finish_doc_signature')
    op.drop_index(op.f('ix_comment_design_id'), table_name='comment_design')
    op.drop_table('comment_design')
    op.drop_index(op.f('ix_stage_id'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_pre_work_doc_id'), table_name='pre_work_doc')
    op.drop_table('pre_work_doc')
    op.drop_index(op.f('ix_order_signature_id'), table_name='order_signature')
    op.drop_table('order_signature')
    op.drop_index(op.f('ix_order_room_id'), table_name='order_room')
    op.drop_table('order_room')
    op.drop_index(op.f('ix_order_check_id'), table_name='order_check')
    op.drop_table('order_check')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_measurement_id'), table_name='measurement')
    op.drop_table('measurement')
    op.drop_index(op.f('ix_finish_doc_id'), table_name='finish_doc')
    op.drop_table('finish_doc')
    op.drop_index(op.f('ix_design_id'), table_name='design')
    op.drop_table('design')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
