"""change finishdo text field name to file

Revision ID: f33467ce434a
Revises: 96dd6389fb0f
Create Date: 2023-04-13 15:11:04.428329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f33467ce434a'
down_revision = '96dd6389fb0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finish_doc', sa.Column('file', sa.String(), nullable=True))
    op.add_column('finish_doc', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('finish_doc', 'text')
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', name='status'),
               nullable=False)
    op.add_column('finish_doc', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('finish_doc', 'created_at')
    op.drop_column('finish_doc', 'file')
    # ### end Alembic commands ###
