"""Add new time fields to pre_work_doc

Revision ID: a368bb217245
Revises: a94cb4c0f0b2
Create Date: 2023-03-23 17:20:36.786083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src import Status

# revision identifiers, used by Alembic.
revision = 'a368bb217245'
down_revision = 'a94cb4c0f0b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status ADD VALUE 'PREWORK_ATTACHED'")
    op.execute("ALTER TYPE status ADD VALUE 'PREWORK_APPROVED'")
    op.execute("ALTER TYPE status ADD VALUE 'PREWORK_DENIED'")
    op.alter_column("order", "status", type_=sa.Enum(Status), nullable=False)
    op.add_column('pre_work_doc', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pre_work_doc', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order", "status", type_=sa.Enum(Status), nullable=False)
    op.execute("ALTER TYPE status DROP VALUE 'PREWORK_ATTACHED'")
    op.execute("ALTER TYPE status DROP VALUE 'PREWORK_APPROVED'")
    op.execute("ALTER TYPE status DROP VALUE 'PREWORK_DENIED'")
    op.drop_column('pre_work_doc', 'updated_at')
    op.drop_column('pre_work_doc', 'created_at')

    # ### end Alembic commands ###
