"""change default value of is_approved field of order_check

Revision ID: 730cffbc0044
Revises: 8de6512707a5
Create Date: 2023-04-13 15:44:07.778319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730cffbc0044'
down_revision = '8de6512707a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', 'FINISH_DOC_ATTACHED', 'CHECK_DECLINED', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', 'FINISH_DOC_ATTACHED', 'CHECK_DECLINED', name='status'),
               nullable=False)
    # ### end Alembic commands ###
