"""add new status for order 'stage_report_attached'

Revision ID: e09c245ef6a9
Revises: 7d8c021999a9
Create Date: 2023-05-26 17:32:00.416465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e09c245ef6a9'
down_revision = '7d8c021999a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', 'FINISH_DOC_ATTACHED', 'CHECK_DECLINED', 'STAGE_REPORT_ATTACHED', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', 'CONTRACT_ATTACHED', 'CONTRACT_SIGNED', 'CHECK_ATTACHED', 'CHECK_APPROVED', 'FINISH_DOC_ATTACHED', 'CHECK_DECLINED', 'STAGE_REPORT_ATTACHED', name='status'),
               nullable=False)
    # ### end Alembic commands ###
