"""enum change status order

Revision ID: 87d2f82ad9a1
Revises: a368bb217245
Create Date: 2023-03-28 10:22:09.220485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87d2f82ad9a1'
down_revision = 'a368bb217245'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', "DESIGN_ATTACHED'DESIGN_DENIED", 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', 'DESIGN_TIME', 'DESIGN_APPROVED', "DESIGN_ATTACHED'DESIGN_DENIED", 'DESIGN_ATTACHED', 'DESIGN_DENIED', 'PREWORK_ATTACHED', 'PREWORK_APPROVED', 'PREWORK_DENIED', name='status'),
               nullable=False)
    # ### end Alembic commands ###
