"""On delete cascade Order related tables

Revision ID: 55eaf7fff8e1
Revises: 39cb4da0b942
Create Date: 2023-03-13 22:32:43.515372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55eaf7fff8e1'
down_revision = '39cb4da0b942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('finish_doc_order_id_fkey', 'finish_doc', type_='foreignkey')
    op.create_foreign_key(None, 'finish_doc', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_check_order_id_fkey', 'order_check', type_='foreignkey')
    op.create_foreign_key(None, 'order_check', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_image_order_room_id_fkey', 'order_image', type_='foreignkey')
    op.create_foreign_key(None, 'order_image', 'order_room', ['order_room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_room_order_id_fkey', 'order_room', type_='foreignkey')
    op.create_foreign_key(None, 'order_room', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'order_room', type_='foreignkey')
    op.create_foreign_key('order_room_order_id_fkey', 'order_room', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_image', type_='foreignkey')
    op.create_foreign_key('order_image_order_room_id_fkey', 'order_image', 'order_room', ['order_room_id'], ['id'])
    op.drop_constraint(None, 'order_check', type_='foreignkey')
    op.create_foreign_key('order_check_order_id_fkey', 'order_check', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'finish_doc', type_='foreignkey')
    op.create_foreign_key('finish_doc_order_id_fkey', 'finish_doc', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
