"""Add created_at filed to Design

Revision ID: bd0fd4c0f462
Revises: 180281c6783e
Create Date: 2023-03-14 13:45:49.493279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0fd4c0f462'
down_revision = '180281c6783e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('NEW', 'APPROVED', 'DENIED', 'APPOINTED', 'MEASURE_TIME', 'MEASURE_ATTACHED', name='status'),
               nullable=False)
    op.drop_column('design', 'created_at')
    # ### end Alembic commands ###
